print("Bienvenido a la veterinaria")
print("Veterinaria 'El mejor amigo del hombre'")
print("EPSISODE I: LA AMENAZA FANTASMA")
print("la federacion de comercio ha bloqueado los planetas de naboo")
print("Los Jedi son enviados a negociar...")